language: ruby
rvm:
  - 2.3.0
script: bundle exec rspec spec
branches:
    only:
        - master
    env:
        global:
              secure: tys5uP1ZgxRFMtNL+wgwaUwb/xHqzi0/Nq1hIrlGkKl0wiwSXF0+lQd7rwnB8lQv/iML5g8jfkpJ9NLcsWuPgwHv0SbE6TBaLl0DEv0FfZPQJAEKW6LnmSPdspHWWQcupOPLNsFsmvFq+a6xli7ireSZSFHSaIXUk4p4wes3NsGTXgGy8JXI6O80KrTjdVSfVtcNJ+YvYCzUVUYtMFPN2UfS4yKlDHOeeIs+w4tnDbHxreHNwXUUYSxTf1d2VMR1h/3+vOqZCzzxY5bjyul/p2GmxtOzhoc4pFJdI2o5Vy3gXSoHJ2d8Rbd3K0co09RDqTLylPk/YonSOPKbXQYWX8gGUwSFJr2lhLmM3oizPFcJo7BmSkOri2Nhx5/4R5RRcFg+antEh2rnSwEMDoR5sD3Axji8qMJHqesizcUc1PQ5PkCgJfQnJwkgrwUl6ohUrafM2H/ysENm4KlYpKOxwigiZn61WEZ0eDt8OUjGr3ADOeehTvQkAgZAvS50JVO781SOu6XVUqrwxIhRGh8+mGdLSARkipJzuHbV67o4eB0TgRJhfLu2FbnIzQQ6STVDtQLSdgO/R2a2FESvhYDAujdDhhmUC8oLJSIApcqnezSmqGZr196pVaNyxrc753+P9a7dmnSLUJTBefc4pQKE1LJDtxKjnkRSKIb+8cMYL64=
